### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by nicolaihoilund** [CodecademyHiddenCourses/Courses#19]
Hey guys.

I did a [concept](https://i.imgur.com/C35xcXz.png) design for a more consistent and pleasing look.
I would be able to implement it if you guys like it.

I honestly don't think that it's worth the effort to categorize the languages. Because all languages are programming languages, JavaScript can be used with Node.js for back-end, Python is sometimes used for data science, and the number of languages overall is too small.

On another note: Would @StevenCopeland be able to give @SoldierCorp and myself write permission, so we can merge and close pull requests?

**Comment by StevenCopeland** [comment]
@nicolaihoilund @SoldierCorp I gave you both write permission.

**Comment by nicolaihoilund** [comment]
@StevenCopeland The new design is live.
Make sure to clear your cache, as I had to (Shift+F5 on Chrome).
The next thing is a favicon.
I'll create a separate issue for it.

Let me know what you think.

**Comment by StevenCopeland** [comment]
@nicolaihoilund 

> That's pretty nice! ~ Despicable Me 3, Gru

**Comment by SoldierCorp** [comment]
Cool and clean design!
