### ISSUE TITLE
Favicon to go along with the new design.

### ISSUE THREAD

**Issue by nicolaihoilund** [CodecademyHiddenCourses/Courses#22]
We need a favicon to go along with the new design.
Please create a pull request with the necessary header tags and the files.

[This](https://realfavicongenerator.net/) will walk you through the process of making it compatible with all devices and providing the tags to copy-paste to the index.html.

**Comment by StevenCopeland** [comment]
@nicolaihoilund I add a favicon. How does it look?

**Comment by casman300** [comment]
Hum, This looked easy enough so gave it a go guess I'm just too slow!

**Comment by nicolaihoilund** [comment]
I'm on mobile, so I'm not able to see the proposed designs. I will take a proper look tomorrow and decide.

Note to new visitors:
If you believe you can make a better version, please give it a try!

**Comment by SoldierCorp** [comment]
That logo that @casman300 is proposing looks great, what do you think?
