### ISSUE TITLE
Make responsive and more attractive

### ISSUE THREAD

**Issue by ravinduramesh** [CodecademyHiddenCourses/Courses#6]
Lets make the website more attractive and responsive including bootstrap

**Comment by StevenCopeland** [comment]
@ravinduramesh I'll invite you to join the org.

**Comment by ravinduramesh** [comment]
Sounds good!!!

**Comment by SoldierCorp** [comment]
So, @ravinduramesh is working on it?

**Comment by ravinduramesh** [comment]
@SoldierCorp  Designed a menu bar. Lets do other styling together.

**Comment by SoldierCorp** [comment]
Sure, once the owner approve your PR I will pull your changes to see what else I can do.

**Comment by nicolaihoilund** [comment]
I created an accordion with all the links.
This could easily be combined with #7.

**Comment by StevenCopeland** [comment]
@SoldierCorp Do you want me to invite you to?

**Comment by StevenCopeland** [comment]
@nicolaihoilund I'll invite you and @SoldierCorp.

**Comment by kaysiz** [comment]
@SoldierCorp invite me too...

**Comment by StevenCopeland** [comment]
@nicolaihoilund Can you change your  PR?

**Comment by StevenCopeland** [comment]
@kaysiz I'll invite you

**Comment by StevenCopeland** [comment]
can you fix the conflicts?

**Comment by nicolaihoilund** [comment]
That would have to be next week. I'm fully booked the next few days. Shouldn't be too hard to do, if anyone else is up for the task.

**Comment by SoldierCorp** [comment]
I'm going to push the following feature:

- Use a `courses.json` to get and write new courses there to show dinamically in the index file.

**Comment by nicolaihoilund** [comment]
I was actually gonna suggest that.
I got tired of copy-pasting very quickly.

Do title, description, url and language keys.

**Comment by StevenCopeland** [comment]
@SoldierCorp Go ahead!

**Comment by SoldierCorp** [comment]
@StevenCopeland I'm about to push the code, but I guess you should to create a new issue for it or it doesn't matter if I use this one to create the PR?

**Comment by ravinduramesh** [comment]
@SoldierCorp  waiting for your JSON file. Could you plz add 'category' also as a key. values will be 'web', 'pro', 'data', etc.

**Comment by ravinduramesh** [comment]
@SoldierCorp You have done it already heh.... Good job!

**Comment by nicolaihoilund** [comment]
The new complete and responsive redesign has been pushed and is now live.
